### PR TITLE
MMIO - Memory Mapped IO

### PR DESCRIPTION
**Pull request by robvanoostenrijk**
Update to IntelHDA engine to support PCI memory mapped IO access.

This prevents additionally transfer of data to a local buffer, but instead reads and writes data directly from the codec memory space.

Additionally added:
- Dynamic EAPD nodes
- Dynamic Custom Commands
- Automatic locating of AppleHDADriver IORegistryEntry
- Match on PCI class against each IntelHDA compatible codec

### CODE REVIEW

**Comment by robvanoostenrijk** [comment]
Debugged and resolved the issues experienced earlier which broke the kext functionality.

**Comment by robvanoostenrijk** [comment]
Now added now IOKit matching. This (together with automatic EAPD node detection), removes the need for most if not all of the configuration.

CodecCommander now attaches to `IOHDACodecFunction`, this allows it to attach on a per codec address basis.
It will only attach to AFG (Audio Function Group) type `IOHDACodecFunction`.

The codec address is retrieved from the parent `IOHDACodecDevice::IOHDACodecAddress`.

IntelHDA finds the parent `IOPCIDevice` in order to send verbs to the Intel HDA codec.
This means that one or more CodecCommanders could be driving the same audio `IOPCIDevice`, but for different  `IOHDACodecDevice::IOHDACodecAddress` instances.

The only problem I have found so far is that it does not work when injecting with Clover.
It only works when installed in /System/Library/Extensions. Since its not replacing a default System kext its not a deal-breaker, but it could be nice if that problem can be resolved.

**Comment by RehabMan** [comment]
Have you merged this pull into master? This is getting very messy...

**Comment by RehabMan** [comment]
I think I may have it figured out... I did 'git checkout origin/master' (my master on github).  Then pulled this one... 'git pull darkvoid/MMIO'.  I think that is it, as opposed to trying to pull this MMIO after pulling your other (4?) requests....  But I will need to test it.  That is for tomorrow.

**Comment by RehabMan** [comment]
Have you tested this?  It doesn't load on my system.  I don't understand how you expect IOKit to match it given the Info.plist.  If you want a kext to load irrespective of device it needs to match on IOResourceMatch=IOKit.

**Comment by RehabMan** [comment]
I think this is failing...
```
    if (mDevice == NULL || mDevice->getDeviceMemoryCount() == 0 || mCodecAddress == 0xFF)
        return false;
```

**Comment by robvanoostenrijk** [comment]
What's your debug output?
Also it only loads when in S /L/E

**Comment by robvanoostenrijk** [comment]
I will collect my debug output for you next boot.
Using SLE it is attaching fine to all IOHDAFunctionGroup objects. Using Clover injection nothing happens.

**Comment by RehabMan** [comment]
I always install to SLE with 'make install_debug'...

The kext is failing in probe.  I added some debug to probe and getHDADriver.  The problem is the ioreg tree is not complete at the time of probe so it fails to find the HDA driver.  As I noted before, the order of drivers loading/executing is multithreaded and therefore unpredictable.  I ran into the same problem when messing around with FakePCIID...

Note: I added a prefix to all debug output so it can be easily filtered for 'CodecCommander'...  I will cleanup all debug output if the kext can be made to work again.

Here is the debug output ():
```
Jan  9 07:34:16 localhost kernel[0]: CodecCommander: CodecCommander: Initializing
Jan  9 07:34:16 localhost kernel[0]: CodecCommander: CodecCommander::probe
Jan  9 07:34:16 localhost kernel[0]: CodecCommander: childEntry->getName()='CodecCommander'
Jan  9 07:34:16 localhost kernel[0]: CodecCommander: groupType=1, mHDADriver=0
 ```
It seems the new attaching scheme is fundamentally flawed.

Also, keep in mind the original version works with both AppleHDA and VoodooHDA.  So searching for things specific to AppleHDA will break the VoodooHDA scenario.

**Comment by robvanoostenrijk** [comment]
Yes, if we cannot attach trustworthily to IOFunctionGroupCodec then it will not work.
Its the only way I can think of though which allows separate CodecCommander instances for each codec.
Unless we write a main loader which loads CodecCommander instances after walking the IORegistry.

**Comment by RehabMan** [comment]
I think probe should not attempt to find mHDADriver just yet.  Probe should succeed, and finding the hda driver should happen as needed later.  Maybe the HDA device can be reliably found in start.  Of course, the VoodooHDA scenario will have to be looked into.

**Comment by robvanoostenrijk** [comment]
I will give that theory a try over here to see if it works more reliably.

**Comment by RehabMan** [comment]
I think that you're finding it not working from Clover/kexts is a sign of something wrong.  Perhaps if you get it working from there instead of SLE might be a good way to test...

**Comment by RehabMan** [comment]
FYI:
```
mIntelHDA->~IntelHDA()
```

should be:
```
delete mIntelHDA;
mIntelHDA = NULL;
```

There may be more instances of this mistake.

**Comment by RehabMan** [comment]
Note: Looking for HDA driver in start has the same problem as probe.  Maybe it should attach to AppleHDADriver node?

**Comment by robvanoostenrijk** [comment]
I will do some more testing with the matching, and if necessary it can be reverted to PCI class matching.

**Comment by RehabMan** [comment]
It works if you match on IOAudioDevice (and move the init code to start).  Code needs to change to capture the mHDADevice (it is then the provider), and the walk up the parent tree to find the IOHDACodecFunction (use IORegistryEntry::compareName).

**Comment by robvanoostenrijk** [comment]
Ok, that sounds good. Should be able to make those changes.
You tested that with Clover injection also?

**Comment by RehabMan** [comment]
I could probably proceed with my merge, and add a commit on top of it for this fix, if you like...  I'll probably commit it as a separate branch for now.

**Comment by RehabMan** [comment]
Let me try Clover kext inject.

**Comment by robvanoostenrijk** [comment]
No worries, no need to do the effort to merge now.

I will roll up the fixes all-in-go tomorrow so it comes into the same pull request.
Just curious if Clover kext injection works.

**Comment by RehabMan** [comment]
Clover inject does not work.
```
Jan  9 09:43:56 localhost com.apple.kextd[19]: Kext id org.tw.CodecCommander not found; removing personalities from kernel.
```

**Comment by robvanoostenrijk** [comment]
Ok, so that might still be a problem then.

As you already highlighted that non-working clover injection is a sign of wrong things.

**Comment by RehabMan** [comment]
Yeah... I wonder what the issue is...

**Comment by RehabMan** [comment]
For a minute there I thought InjectKexts=Detect wasn't working properly or the existence of FakePCIID in SLE was confusing Clover.  But now I see that it is because I have a custom entry and /SystemParameters/InjectKexts=Detect is ignored in this case and the custom entry takes over.  I should probably add Detect to my custom entry so I'm not confused next time.

Bottom line: This kext does not work with injection.  It is something OS X is doing (throwing it out) due to an issue I don't understand.  Could be a Clover bug.

**Comment by RehabMan** [comment]
Some code you might find useful...
```
static IORegistryEntry* searchParentByClass(IORegistryEntry* registryEntry, const char* className)
{
	OSString* strName = OSString::withCStringNoCopy(className);
	while (NULL != registryEntry)
	{
		DEBUG_LOG("registryEntry->getName()='%s'\n", registryEntry->getName());
		if (registryEntry->compareName(strName))
			break;
		registryEntry = registryEntry->getParentEntry(gIOServicePlane);
	}
	return registryEntry;
}
```

**Comment by RehabMan** [comment]
I'm doing some experimentation with VoodooHDA.  After I installed the latest version (built from sources), it greeted me with a panic on boot (nice...).  Fixed that problem by mapping the backtrace -> disassembly -> source.  It was calling kern_os_malloc(0) and not expecting the NULL return, and now have it working.  

Although it still needs tweaks (not all speakers are working, and HDMI audio doesn't work... reading the Intel HDA spec now), it is working, and furthermore, CodecCommander is not needed after sleep to wake the EAPD nodes!  With only minor changes the CodecCommander.kext can be adjusted to account for VoodooHDA (don't check for IOHDACodecFunction, property "IOHDACodecFunctionGroupType"), just in case some people need it.

**Comment by robvanoostenrijk** [comment]
So in short, VoodooHDA already does EAPD and CodecCommander is only required in the AppleHDA use-case?
I have not started on CodecCommander yet, working on BrcmPatchRAM at the moment.
Should be starting to fix up the currently problems in one or two days.

**Comment by RehabMan** [comment]
There is definitely references in VoodooHDA source for EAPD, so yes, it could be that newer versions have it built in, and older versions don't (I know people have used CodecCommander for VoodooHDA in the past).

**Comment by robvanoostenrijk** [comment]
Did you manage to get CodecCommander to match to IOAudioDevice through Clover injection?
Maybe `ForceKextsToLoad` might be of help here.

**Comment by RehabMan** [comment]
I did not.  The kextd keeps throwing it out (see above a few posts)...

ForceKextsToLoad is useful for forcing dependencies to load (that are in /S/L/E), but I don't see any dependencies for CodecCommander that are not likely to already be loaded...

I don't use Clover kext injection as it is too flakey (except for Recovery/Installer), so it doesn't bother me.

**Comment by robvanoostenrijk** [comment]
Ok. I will look into it.
Just finished off BrcmPatchRAM. It has a new concept of dynamically publishing personalities into the IOCatalogue, I think thats something which might interest you.

**Comment by robvanoostenrijk** [comment]
I have now changed the code as per our discussion.
IOCodecCommander is now driven by IOAudioEngine. Additionally also the IOAudioEngine class itself is used internally to obtain the IOAudioDevicePowerState instead of reading it from the IORegistry.

**Comment by the-darkvoid** [comment]
Codec Commander now allows configuration for each specific codec in a system, i.e. "Codec Profile", instead of for an entire platform.

This is used to resolve the static noise headphones problem on the Realtek ALC668 codec.

**Pull request merged**
